//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductoES.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_producto
    {
        public int id_producto { get; set; }
        public string nombre_producto { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> precio_unitario { get; set; }
        public Nullable<int> categoria_id { get; set; }
        public Nullable<int> marca_id { get; set; }
        public Nullable<int> medida_id { get; set; }
        public Nullable<int> proveedor_id { get; set; }
    
        public virtual tb_categoria tb_categoria { get; set; }
        public virtual tb_marca tb_marca { get; set; }
        public virtual tb_medida tb_medida { get; set; }
        public virtual tb_proveedor tb_proveedor { get; set; }
    }
}
